"""Script - Iartes( Caso de Teste + CSV).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WpQKvYVIn_Az88Vb0bt1x08wlhD6sIq-
"""

import base64
import json
import logging
import re
import zipfile
from pathlib import Path

import pandas as pd
from langchain_ollama import ChatOllama

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%H:%M:%S",
)
log = logging.getLogger(__name__)

BASE_DIR = Path(__file__).resolve().parent

# Configurações
APK_ZIP = BASE_DIR / "apks/moneytracker_38.apk"
OUTPUT_DIR = BASE_DIR / "output"
CSV_OUT = BASE_DIR / "Csv.csv"
JSON_OUT = BASE_DIR / "Json.json"
CONTENT_DIR = BASE_DIR / "content"

CONTENT_DIR.mkdir(parents=True, exist_ok=True)

log.info("BASE_DIR    : %s", BASE_DIR)
log.info("APK_ZIP     : %s", APK_ZIP)
log.info("OUTPUT_DIR  : %s", OUTPUT_DIR)
log.info("CONTENT_DIR : %s", CONTENT_DIR)
log.info("CSV_OUT     : %s", CSV_OUT)
log.info("JSON_OUT    : %s", JSON_OUT)

client = ChatOllama(base_url="http://localhost:11434", model="gemma3:4b")
log.info("Ollama client inicializado (model=gemma3:4b)")


def encontrar_screenshots(apk_path: Path, output_dir: Path = OUTPUT_DIR) -> list[Path]:
    """Retorna todas as screenshots em output_dir que correspondem ao nome da APK.

    A correspondência é feita pelo nome base da APK (sem versão nem extensão)
    contra o nome dos diretórios de primeiro nível em output_dir.
    Ex: 'moneytracker_38.apk' -> busca diretórios contendo 'moneytracker'.
    """
    # e.g. 'moneytracker_38.apk' -> 'moneytracker'
    base_name = Path(apk_path).stem.split("_")[0].lower()
    screenshots: list[Path] = []

    if not output_dir.exists():
        log.warning("Pasta de output não encontrada: %s", output_dir)
        return screenshots

    for app_dir in output_dir.iterdir():
        if app_dir.is_dir() and base_name in app_dir.name.lower():
            log.info("Diretório correspondente encontrado: %s", app_dir.name)
            for ext in ("png", "jpg", "jpeg"):
                screenshots.extend(app_dir.rglob(f"screenshots/*.{ext}"))

    screenshots.sort()
    log.info("%d screenshot(s) encontrada(s) para '%s'", len(screenshots), base_name)
    return screenshots


def extrair_info_apk(caminho_zip):
    log.info("Extraindo componentes do APK: %s", caminho_zip)
    componentes = []
    pacote = "com.blogspot.e_kanivets.moneytracker"
    try:
        with zipfile.ZipFile(caminho_zip, "r") as z:
            for xml in [f for f in z.namelist() if f.endswith(".xml")]:
                conteudo = z.read(xml).decode("utf-8", errors="ignore")
                matches = re.finditer(r'android:id="@+id/([^"]+)"', conteudo)
                for m in matches:
                    id_nome = m.group(1)
                    componentes.append({"id_curto": id_nome.lower(), "id_real": id_nome})
    except Exception as e:
        log.warning("Falha ao ler APK '%s': %s", caminho_zip, e)
    log.info("%d componente(s) extraído(s) do APK (pacote: %s)", len(componentes), pacote)
    return componentes, pacote


def analise_qa_analista(caminho_arquivo, tipo="texto"):
    log.debug("Analisando [%s]: %s", tipo, caminho_arquivo)

    prompt = (
        "Aja como QA Sênior. Extraia os passos de teste do log/imagem fornecido.\n"
        "REGRAS DE OURO:\n"
        "1. DESCRIÇÃO: Não use 'Ações exploratórias'. Descreva a ação real (ex: 'Inserir Título', 'Clicar em Cancelar').\n"
        "2. VALOR: Remova prefixos como 'valor:' ou 'texto:'. Deixe APENAS o dado (ex: '6', 'Refeição').\n"
        "3. ID_TECNICO: Identifique o ID do elemento no log (ex: 'etprice', 'btn_save').\n"
        "4. RESULTADO: Descreva o que deve acontecer em PT-BR.\n\n"
        'Retorne APENAS o JSON: {"fluxo": [{"Descricao": "", "Esperado": "", "Activity": "", "ID_Bruto": "", "Acao": "", "Valor": ""}]}'
    )
    try:
        if tipo == "imagem":
            with open(caminho_arquivo, "rb") as f:
                b64 = base64.b64encode(f.read()).decode("utf-8")
            msg = [
                {
                    "role": "user",
                    "content": [
                        {"type": "text", "text": prompt},
                        {"type": "image_url", "image_url": {"url": f"data:image/png;base64,{b64}"}},
                    ],
                }
            ]
        else:
            with open(caminho_arquivo, encoding="utf-8", errors="ignore") as f:
                texto = f.read()
            msg = [{"role": "user", "content": f"{prompt}\n\nCONTEUDO:\n{texto}"}]

        log.debug("Chamando LLM...")
        res = client.invoke(msg)
        raw = res.content
        if isinstance(raw, str):
            content = raw
        elif isinstance(raw, list):
            first = raw[0]
            content = first["text"] if isinstance(first, dict) else str(first)
        else:
            content = str(raw)
        parsed = json.loads(content.replace("```json", "").replace("```", "").strip())
        log.debug("LLM retornou %d passo(s)", len(parsed.get("fluxo", [])))
        return parsed
    except json.JSONDecodeError as e:
        log.warning("Falha ao parsear JSON da resposta LLM (%s): %s", caminho_arquivo, e)
        log.debug("Conteúdo bruto recebido: %s", content if "content" in dir() else "N/A")
        return None
    except Exception as e:
        log.error("Erro inesperado ao analisar '%s': %s", caminho_arquivo, e)
        return None


comp_apk, pacote_base = extrair_info_apk(APK_ZIP)
dataset_qa = []

screenshots = encontrar_screenshots(APK_ZIP)
log.info("Iniciando processamento de %d screenshot(s)...", len(screenshots))

for i, screenshot in enumerate(screenshots, start=1):
    log.info("[%d/%d] Processando: %s", i, len(screenshots), screenshot.name)
    resultado = analise_qa_analista(screenshot, "imagem")

    if resultado and "fluxo" in resultado:
        passos = resultado["fluxo"]
        log.info("  -> %d passo(s) extraído(s)", len(passos))
        for passo in passos:
            # Tenta casar o ID extraído pela IA com o ID real do APK
            id_ia = str(passo.get("ID_Bruto", "")).lower()
            id_final = next(
                (
                    f"{pacote_base}:id/{item['id_real']}"
                    for item in comp_apk
                    if item["id_curto"] in id_ia
                ),
                f"{pacote_base}:id/{id_ia}",
            )

            ct_id = f"CT_{len(dataset_qa) + 1:03d}"
            entrada = {
                "CT_ID": ct_id,
                "Tipo": "Funcional",
                "Descrição": passo.get("Descricao"),
                "Resultado_Esperado": passo.get("Esperado"),
                "Activity": passo.get("Activity"),
                "ID_Tecnico": id_final,
                "Acao": passo.get("Acao"),
                "Valor": passo.get("Valor"),
            }
            dataset_qa.append(entrada)

            ct_file = CONTENT_DIR / f"{ct_id}.json"
            ct_file.write_text(json.dumps(entrada, indent=4, ensure_ascii=False), encoding="utf-8")
            log.debug("  Passo salvo: %s", ct_file.name)
    else:
        log.warning("  -> Nenhum fluxo retornado para: %s", screenshot.name)

log.info("Total de casos de teste coletados: %d", len(dataset_qa))

if dataset_qa:
    pd.DataFrame(dataset_qa).to_csv(CSV_OUT, index=False)
    log.info("CSV salvo em: %s", CSV_OUT)
    with open(JSON_OUT, "w", encoding="utf-8") as f:
        json.dump(dataset_qa, f, indent=4, ensure_ascii=False)
    log.info("JSON salvo em: %s", JSON_OUT)
    log.info("PROCESSAMENTO CONCLUÍDO. TOTAL: %d", len(dataset_qa))
else:
    log.warning("Nenhum caso de teste gerado. Verifique as screenshots e a conexão com o Ollama.")
