"""Script - Iartes(extração_info_app).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TNz6eSS8mmCPA5z_enJt4mEX8J_zn4do
"""

import json
import os
import re
import zipfile
from pathlib import Path

import pandas as pd
from langchain_ollama import ChatOllama

client = ChatOllama(model="gemma3:4b", base_url="http://localhost:11434")


def find_manifest_file(zip_file):
    for file_name in zip_file.namelist():
        if file_name.endswith("AndroidManifest.xml"):
            return file_name
    return None


def extract_activities_from_manifest(content):
    return re.findall(r'<activity[^>]*android:name="([^"]+)"', content)


def extract_ids_from_line(line):
    match = re.search(r'android:id="([^"]+)"', line)
    return match.group(1) if match else None


def extract_ids_from_content(content):
    ids = []
    for line in content.splitlines():
        id_value = extract_ids_from_line(line)
        if id_value:
            ids.append(f'android:id="{id_value}"')
    return ids


def extract_apk_mapping(file_path: Path):
    app_info = {"package_name": None, "activities": [], "component_ids": []}
    try:
        with zipfile.ZipFile(file_path, "r") as zip_file:
            manifest_file = find_manifest_file(zip_file)
            if manifest_file:
                with zip_file.open(manifest_file) as f:
                    manifest_content = f.read().decode("utf-8", errors="ignore")
                package_match = re.search(r'\bpackage="([^"]+)"', manifest_content)
                app_info["package_name"] = (
                    package_match.group(1) if package_match else "Não disponível"
                )
                activities = extract_activities_from_manifest(manifest_content)
                app_info["activities"] = [activity.lstrip(".") for activity in activities]

            xml_files = [f for f in zip_file.namelist() if f.endswith(".xml")]
            ids_lines = []
            for file_name in xml_files:
                with zip_file.open(file_name) as f:
                    try:
                        xml_content = f.read().decode("utf-8", errors="ignore")
                        ids = extract_ids_from_content(xml_content)
                        for id_val in ids:
                            ids_lines.append({"file": file_name, "id": id_val})
                    except:
                        continue
            app_info["component_ids"] = ids_lines
    except Exception as e:
        print(e)
    return app_info


if __name__ == "__main__":
    BASE_DIR = Path(__file__).resolve().parent
    file_path = BASE_DIR / "apks/budget-watch-master.zip"

    if os.path.exists(file_path):
        info = extract_apk_mapping(file_path)

        json_data = json.dumps(info, indent=4, ensure_ascii=False)
        print(json_data)
        with open("info.json", "w", encoding="utf-8") as f:
            f.write(json_data)

        df = pd.DataFrame(info["component_ids"])
        if df.empty:
            df = pd.DataFrame([{"package_name": info["package_name"]}])

        print(df.to_csv(index=False))
        df.to_csv("info.csv", index=False)
