"""Script - Iartes( Caso de Teste + CSV).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WpQKvYVIn_Az88Vb0bt1x08wlhD6sIq-
"""

import base64
import json
import os
import re
import shutil
import zipfile
from pathlib import Path

import pandas as pd
from langchain_ollama import ChatOllama
from rich.console import Console
from rich.panel import Panel
from rich.progress import BarColumn, Progress, SpinnerColumn, TaskProgressColumn, TextColumn
from rich.table import Table

console = Console()

BASE_DIR = Path(__file__).resolve().parent

# Configurações
APK_ZIP = BASE_DIR / "apks" / "budget-watch-master.zip"
OUTPUT_DIR = BASE_DIR / "output"
CONTENT_DIR = BASE_DIR / "content"
PASTA_DESTINO = CONTENT_DIR / "Telas"
TELAS_ZIP = CONTENT_DIR / "Telas.zip"


def zipar_test_cases(apk_path: Path, output_dir: Path, dest_zip: Path) -> None:
    """Zipa todos os arquivos test_cases do APK encontrado em output_dir."""
    base_name = re.split(r"[-_]", apk_path.stem)[0].lower()
    arquivos: list[Path] = [
        f
        for app_dir in output_dir.iterdir()
        if app_dir.is_dir() and base_name in app_dir.name.lower()
        for f in app_dir.rglob("test_cases/*")
        if f.is_file()
    ]
    console.print(
        f"[cyan]zipar_test_cases[/] → [bold]{len(arquivos)}[/] "
        f"arquivo(s) encontrado(s) para '[yellow]{base_name}[/]'"
    )
    dest_zip.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(dest_zip, "w", zipfile.ZIP_DEFLATED) as zf:
        for arq in arquivos:
            zf.write(arq, arq.name)
    console.print(f"  ZIP gerado: [dim]{dest_zip}[/]")


console.print(Panel("[bold]Iniciando pipeline Iartes[/]", style="blue"))
console.print(f"[dim]APK:[/] {APK_ZIP}")
console.print(f"[dim]Output:[/] {OUTPUT_DIR}")

zipar_test_cases(APK_ZIP, OUTPUT_DIR, TELAS_ZIP)

if PASTA_DESTINO.exists():
    shutil.rmtree(PASTA_DESTINO)
PASTA_DESTINO.mkdir(parents=True)
with zipfile.ZipFile(TELAS_ZIP, "r") as zip_ref:
    zip_ref.extractall(PASTA_DESTINO)
console.print(f"[green]✓[/] Telas extraídas em [dim]{PASTA_DESTINO}[/]")

client = ChatOllama(model="gemma3:4b", base_url="http://localhost:11434")
console.print("[green]✓[/] Ollama client pronto [dim](gemma3:4b)[/]")


def extrair_info_apk(caminho_zip):
    console.print(f"\n[cyan]Extraindo componentes do APK:[/] [dim]{caminho_zip.name}[/]")
    componentes = []
    pacote = "com.blogspot.e_kanivets.moneytracker"
    try:
        with zipfile.ZipFile(caminho_zip, "r") as z:
            for xml in [f for f in z.namelist() if f.endswith(".xml")]:
                conteudo = z.read(xml).decode("utf-8", errors="ignore")
                matches = re.finditer(r'android:id="@+id/([^"]+)"', conteudo)
                for m in matches:
                    id_nome = m.group(1)
                    componentes.append({"id_curto": id_nome.lower(), "id_real": id_nome})
    except Exception as e:
        console.print(f"  [red]✗ Falha ao ler APK:[/] {e}")
    console.print(f"  [green]✓[/] {len(componentes)} componente(s) extraído(s)")
    return componentes, pacote


def analise_qa_analista(caminho_arquivo, tipo="texto"):
    prompt = (
        "Aja como QA Sênior. Extraia os passos de teste do log/imagem fornecido.\n"
        "REGRAS DE OURO:\n"
        "1. DESCRIÇÃO: Não use 'Ações exploratórias'. Descreva a ação real (ex: 'Inserir Título', 'Clicar em Cancelar').\n"
        "2. VALOR: Remova prefixos como 'valor:' ou 'texto:'. Deixe APENAS o dado (ex: '6', 'Refeição').\n"
        "3. ID_TECNICO: Identifique o ID do elemento no log (ex: 'etprice', 'btn_save').\n"
        "4. RESULTADO: Descreva o que deve acontecer em PT-BR.\n\n"
        'Retorne APENAS o JSON: {"fluxo": [{"Descricao": "", "Esperado": "", "Activity": "", "ID_Bruto": "", "Acao": "", "Valor": ""}]}'
    )
    try:
        if tipo == "imagem":
            with open(caminho_arquivo, "rb") as f:
                b64 = base64.b64encode(f.read()).decode("utf-8")
            msg = [
                {
                    "role": "user",
                    "content": [
                        {"type": "text", "text": prompt},
                        {"type": "image_url", "image_url": {"url": f"data:image/png;base64,{b64}"}},
                    ],
                }
            ]
        else:
            with open(caminho_arquivo, encoding="utf-8", errors="ignore") as f:
                texto = f.read()
            msg = [{"role": "user", "content": f"{prompt}\n\nCONTEUDO:\n{texto}"}]

        res = client.invoke(msg)
        raw = res.content
        if isinstance(raw, str):
            content = raw
        elif isinstance(raw, list):
            first = raw[0]
            content = first["text"] if isinstance(first, dict) else str(first)
        else:
            content = str(raw)
        return json.loads(content.replace("```json", "").replace("```", "").strip())
    except json.JSONDecodeError as e:
        console.print(f"    [red]✗ JSON inválido:[/] {e}")
        return None
    except Exception as e:
        console.print(f"    [red]✗ Erro LLM:[/] {e}")
        return None


comp_apk, pacote_base = extrair_info_apk(APK_ZIP)
dataset_qa = []

arquivos = [
    (os.path.join(root, nome), nome)
    for root, _, files in os.walk(PASTA_DESTINO)
    for nome in files
    if not nome.startswith(".") and "MACOSX" not in root
]

console.print(Panel(f"[bold]Processando {len(arquivos)} arquivo(s)[/]", style="blue"))

with Progress(
    SpinnerColumn(),
    TextColumn("[progress.description]{task.description}"),
    BarColumn(),
    TaskProgressColumn(),
    console=console,
) as progress:
    task = progress.add_task("Aguardando...", total=len(arquivos))

    for caminho, nome in arquivos:
        tipo = "imagem" if nome.lower().endswith(("png", "jpg", "jpeg")) else "texto"
        progress.update(task, description=f"[cyan]{nome}[/]")

        resultado = analise_qa_analista(caminho, tipo)

        if resultado and "fluxo" in resultado:
            passos = resultado["fluxo"]
            progress.console.print(
                f"  [green]✓[/] {nome} → [bold]{len(passos)}[/] passo(s)"
            )
            for passo in passos:
                id_ia = str(passo.get("ID_Bruto", "")).lower()
                id_final = next(
                    (
                        f"{pacote_base}:id/{item['id_real']}"
                        for item in comp_apk
                        if item["id_curto"] in id_ia
                    ),
                    f"{pacote_base}:id/{id_ia}",
                )
                dataset_qa.append(
                    {
                        "CT_ID": f"CT_{len(dataset_qa) + 1:03d}",
                        "Tipo": "Funcional",
                        "Descrição": passo.get("Descricao"),
                        "Resultado_Esperado": passo.get("Esperado"),
                        "Activity": passo.get("Activity"),
                        "ID_Tecnico": id_final,
                        "Acao": passo.get("Acao"),
                        "Valor": passo.get("Valor"),
                    }
                )
        else:
            progress.console.print(f"  [yellow]⚠[/] {nome} → sem fluxo retornado")

        progress.advance(task)

if dataset_qa:
    tabela = Table(title=f"Casos de Teste Gerados ({len(dataset_qa)})", show_lines=True)
    tabela.add_column("CT_ID", style="bold cyan", no_wrap=True)
    tabela.add_column("Activity", style="dim")
    tabela.add_column("Descrição")
    tabela.add_column("Ação", style="magenta")
    for ct in dataset_qa:
        tabela.add_row(
            ct["CT_ID"],
            ct.get("Activity") or "",
            ct.get("Descrição") or "",
            ct.get("Acao") or "",
        )
    console.print(tabela)

    pd.DataFrame(dataset_qa).to_csv("Csv.csv", index=False)
    with open("Json.json", "w", encoding="utf-8") as f:
        json.dump(dataset_qa, f, indent=4, ensure_ascii=False)
    console.print(
        f"\n[bold green]✓ CONCLUÍDO[/] — {len(dataset_qa)} caso(s) salvos em Csv.csv e Json.json"
    )
else:
    console.print(
        "[bold red]✗ Nenhum caso de teste gerado.[/] "
        "Verifique os arquivos e a conexão com o Ollama."
    )
