"""Script - Iartes( CSV).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iJwoweNgd9uzZz-iNddrZlkLWRFUeeQp
"""

import base64
import json
import os
import re
import shutil
import zipfile

import pandas as pd
from openai import OpenAI

os.environ["OPENAI_API_KEY"] = "SUA CHAVE AQUI"

PASTA_DESTINO = "/content/Telas"
APK_ZIP = "/content/moneytracker.zip"
TELAS_ZIP = "/content/Telas.zip"

if os.path.exists(PASTA_DESTINO):
    shutil.rmtree(PASTA_DESTINO)
os.makedirs(PASTA_DESTINO)

with zipfile.ZipFile(TELAS_ZIP, "r") as zip_ref:
    zip_ref.extractall(PASTA_DESTINO)

client = OpenAI()
MODEL_NAME = "gpt-4o-mini"


def extrair_base_conhecimento_apk(caminho_zip):
    componentes = []
    pacote = "com.blogspot.e_kanivets.moneytracker"
    try:
        with zipfile.ZipFile(caminho_zip, "r") as z:
            xml_files = [f for f in z.namelist() if f.endswith(".xml")]
            for xml in xml_files:
                with z.open(xml) as f:
                    conteudo = f.read().decode("utf-8", errors="ignore")
                    # Captura IDs e tenta identificar o tipo da View (Button, EditText, etc)
                    matches = re.finditer(r'<([\w.]+)[^>]+android:id="@+id/([^"]+)"', conteudo)
                    for m in matches:
                        tipo_view = m.group(1).split(".")[-1]
                        id_nome = m.group(2)
                        componentes.append(
                            {
                                "field": tipo_view,
                                "id_completo": f"{pacote}:id/{id_nome}",
                                "id_curto": id_nome,
                            }
                        )
    except Exception:
        pass
    return componentes


def processar_texto_qa(caminho_arquivo, tipo="texto"):
    prompt = (
        "Analise o log de teste Android e extraia as ações para um JSON puro. "
        "Use obrigatoriamente estes campos: "
        "activity (caminho completo), field (tipo do componente), id_ref (id mencionado), action_type, value. "
        "Exemplo de action_type: click, type, select. "
        'Retorne apenas o objeto JSON: {"acoes": []}'
    )

    try:
        if tipo == "imagem":
            with open(caminho_arquivo, "rb") as f:
                b64 = base64.b64encode(f.read()).decode("utf-8")
            msg = [
                {
                    "role": "user",
                    "content": [
                        {"type": "text", "text": prompt},
                        {"type": "image_url", "image_url": {"url": f"data:image/png;base64,{b64}"}},
                    ],
                }
            ]
        else:
            with open(caminho_arquivo, encoding="utf-8", errors="ignore") as f:
                texto = f.read()
            msg = [{"role": "user", "content": prompt + f"\n\nTexto: {texto}"}]

        res = client.chat.completions.create(model=MODEL_NAME, messages=msg, temperature=0.0)
        return json.loads(
            res.choices[0].message.content.replace("```json", "").replace("```", "").strip()
        )
    except Exception:
        return


def encontrar_melhor_id(id_mencionado, base_apk):
    if not id_mencionado:
        return "N/A", "View"
    limpo = id_mencionado.replace("@+id/", "").replace("id/", "").lower()
    for item in base_apk:
        if limpo == item["id_curto"].lower():
            return item["id_completo"], item["field"]
    return f"com.blogspot.e_kanivets.moneytracker:id/{limpo}", "View"


base_apk = extrair_base_conhecimento_apk(APK_ZIP)
dataset_final = []

for root, _, files in os.walk(PASTA_DESTINO):
    for nome in files:
        if nome.startswith(".") or "MACOSX" in root:
            continue

        caminho = os.path.join(root, nome)
        tipo = "imagem" if nome.lower().endswith(("png", "jpg", "jpeg")) else "texto"

        resultado = processar_texto_qa(caminho, tipo)
        if resultado and "acoes" in resultado:
            for acao in resultado["acoes"]:
                id_real, tipo_real = encontrar_melhor_id(acao.get("id_ref"), base_apk)

                dataset_final.append(
                    {
                        "activity": acao.get("activity", "UnknownActivity").replace("/.", "."),
                        "field": tipo_real if tipo_real != "View" else acao.get("field", "View"),
                        "id": id_real,
                        "action_type": acao.get("action_type", "click"),
                        "value": acao.get("value", ""),
                    }
                )

if dataset_final:
    df = pd.DataFrame(dataset_final)
    # Reordenando colunas para o padrão solicitado
    df = df[["activity", "field", "id", "action_type", "value"]]
    df.to_csv("/content/dataset_automacao.csv", index=False)
    with open("/content/dataset_automacao.json", "w", encoding="utf-8") as f:
        json.dump(dataset_final, f, indent=4)
    print(f"Dataset gerado com {len(dataset_final)} linhas.")
