"""Script - Iartes( CSV).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iJwoweNgd9uzZz-iNddrZlkLWRFUeeQp
"""

import base64
import json
import os
import re
import shutil
import zipfile
from pathlib import Path

import pandas as pd
from langchain_ollama import ChatOllama
from rich.console import Console
from rich.panel import Panel
from rich.progress import BarColumn, Progress, SpinnerColumn, TaskProgressColumn, TextColumn
from rich.table import Table

console = Console()

BASE_DIR = Path(__file__).resolve().parent

# Configurações
APK_ZIP = BASE_DIR / "apks" / "budget-watch-master.zip"
OUTPUT_DIR = BASE_DIR / "output"
CONTENT_DIR = BASE_DIR / "content"
PASTA_DESTINO = CONTENT_DIR / "Telas"
TELAS_ZIP = CONTENT_DIR / "Telas.zip"
CSV_OUT = BASE_DIR / "dataset_automacao.csv"
JSON_OUT = BASE_DIR / "dataset_automacao.json"


def zipar_test_cases(apk_path: Path, output_dir: Path, dest_zip: Path) -> None:
    """Zipa todos os arquivos test_cases do APK encontrado em output_dir."""
    base_name = re.split(r"[-_]", apk_path.stem)[0].lower()
    arquivos: list[Path] = [
        f
        for app_dir in output_dir.iterdir()
        if app_dir.is_dir() and base_name in app_dir.name.lower()
        for f in app_dir.rglob("test_cases/*")
        if f.is_file()
    ]
    console.print(
        f"[cyan]zipar_test_cases[/] → [bold]{len(arquivos)}[/] "
        f"arquivo(s) encontrado(s) para '[yellow]{base_name}[/]'"
    )
    dest_zip.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(dest_zip, "w", zipfile.ZIP_DEFLATED) as zf:
        for arq in arquivos:
            zf.write(arq, arq.name)
    console.print(f"  ZIP gerado: [dim]{dest_zip}[/]")


console.print(Panel("[bold]Iniciando pipeline Iartes CSV[/]", style="blue"))
console.print(f"[dim]APK:[/] {APK_ZIP}")
console.print(f"[dim]Output:[/] {OUTPUT_DIR}")

zipar_test_cases(APK_ZIP, OUTPUT_DIR, TELAS_ZIP)

if PASTA_DESTINO.exists():
    shutil.rmtree(PASTA_DESTINO)
PASTA_DESTINO.mkdir(parents=True)
with zipfile.ZipFile(TELAS_ZIP, "r") as zip_ref:
    zip_ref.extractall(PASTA_DESTINO)
console.print(f"[green]✓[/] Telas extraídas em [dim]{PASTA_DESTINO}[/]")

client = ChatOllama(model="gemma3:4b", base_url="http://localhost:11434")
console.print("[green]✓[/] Ollama client pronto [dim](gemma3:4b)[/]")


def extrair_base_conhecimento_apk(caminho_zip: Path):
    console.print(
        f"\n[cyan]Extraindo base de conhecimento do APK:[/] [dim]{caminho_zip.name}[/]"
    )
    componentes = []
    pacote = "com.blogspot.e_kanivets.moneytracker"
    try:
        with zipfile.ZipFile(caminho_zip, "r") as z:
            for xml in [f for f in z.namelist() if f.endswith(".xml")]:
                with z.open(xml) as f:
                    conteudo = f.read().decode("utf-8", errors="ignore")
                    matches = re.finditer(
                        r'<([\w.]+)[^>]+android:id="@+id/([^"]+)"', conteudo
                    )
                    for m in matches:
                        tipo_view = m.group(1).split(".")[-1]
                        id_nome = m.group(2)
                        componentes.append(
                            {
                                "field": tipo_view,
                                "id_completo": f"{pacote}:id/{id_nome}",
                                "id_curto": id_nome,
                            }
                        )
    except Exception as e:
        console.print(f"  [red]✗ Falha ao ler APK:[/] {e}")
    console.print(f"  [green]✓[/] {len(componentes)} componente(s) extraído(s)")
    return componentes


def processar_texto_qa(caminho_arquivo, tipo="texto"):
    prompt = (
        "Analise o log de teste Android e extraia as ações para um JSON puro. "
        "Use obrigatoriamente estes campos: "
        "activity (caminho completo), field (tipo do componente), id_ref (id mencionado), action_type, value. "
        "Exemplo de action_type: click, type, select. "
        'Retorne apenas o objeto JSON: {"acoes": []}'
    )
    try:
        if tipo == "imagem":
            with open(caminho_arquivo, "rb") as f:
                b64 = base64.b64encode(f.read()).decode("utf-8")
            msg = [
                {
                    "role": "user",
                    "content": [
                        {"type": "text", "text": prompt},
                        {"type": "image_url", "image_url": {"url": f"data:image/png;base64,{b64}"}},
                    ],
                }
            ]
        else:
            with open(caminho_arquivo, encoding="utf-8", errors="ignore") as f:
                texto = f.read()
            msg = [{"role": "user", "content": prompt + f"\n\nTexto: {texto}"}]

        res = client.invoke(msg)
        raw = res.content
        if isinstance(raw, str):
            content = raw
        elif isinstance(raw, list):
            first = raw[0]
            content = first["text"] if isinstance(first, dict) else str(first)
        else:
            content = str(raw)
        return json.loads(content.replace("```json", "").replace("```", "").strip())
    except json.JSONDecodeError as e:
        console.print(f"    [red]✗ JSON inválido:[/] {e}")
        return None
    except Exception as e:
        console.print(f"    [red]✗ Erro LLM:[/] {e}")
        return None


def encontrar_melhor_id(id_mencionado, base_apk):
    if not id_mencionado:
        return "N/A", "View"
    limpo = id_mencionado.replace("@+id/", "").replace("id/", "").lower()
    for item in base_apk:
        if limpo == item["id_curto"].lower():
            return item["id_completo"], item["field"]
    return f"com.blogspot.e_kanivets.moneytracker:id/{limpo}", "View"


base_apk = extrair_base_conhecimento_apk(APK_ZIP)
dataset_final = []

arquivos = [
    (os.path.join(root, nome), nome)
    for root, _, files in os.walk(PASTA_DESTINO)
    for nome in files
    if not nome.startswith(".") and "MACOSX" not in root
]

console.print(Panel(f"[bold]Processando {len(arquivos)} arquivo(s)[/]", style="blue"))

with Progress(
    SpinnerColumn(),
    TextColumn("[progress.description]{task.description}"),
    BarColumn(),
    TaskProgressColumn(),
    console=console,
) as progress:
    task = progress.add_task("Aguardando...", total=len(arquivos))

    for caminho, nome in arquivos:
        tipo = "imagem" if nome.lower().endswith(("png", "jpg", "jpeg")) else "texto"
        progress.update(task, description=f"[cyan]{nome}[/]")

        resultado = processar_texto_qa(caminho, tipo)

        if resultado and "acoes" in resultado:
            acoes = resultado["acoes"]
            progress.console.print(
                f"  [green]✓[/] {nome} → [bold]{len(acoes)}[/] ação(ões)"
            )
            for acao in acoes:
                id_real, tipo_real = encontrar_melhor_id(acao.get("id_ref"), base_apk)
                dataset_final.append(
                    {
                        "activity": acao.get("activity", "UnknownActivity").replace("/.", "."),
                        "field": tipo_real if tipo_real != "View" else acao.get("field", "View"),
                        "id": id_real,
                        "action_type": acao.get("action_type", "click"),
                        "value": acao.get("value", ""),
                    }
                )
        else:
            progress.console.print(f"  [yellow]⚠[/] {nome} → sem ações retornadas")

        progress.advance(task)

if dataset_final:
    tabela = Table(
        title=f"Dataset de Automação ({len(dataset_final)} ações)", show_lines=True
    )
    tabela.add_column("Activity", style="dim")
    tabela.add_column("Field", style="cyan")
    tabela.add_column("ID", style="dim")
    tabela.add_column("Action", style="magenta")
    tabela.add_column("Value")
    for row in dataset_final:
        tabela.add_row(
            row["activity"],
            row["field"],
            row["id"],
            row["action_type"],
            row.get("value") or "",
        )
    console.print(tabela)

    df = pd.DataFrame(dataset_final)[["activity", "field", "id", "action_type", "value"]]
    df.to_csv(CSV_OUT, index=False)
    with open(JSON_OUT, "w", encoding="utf-8") as f:
        json.dump(dataset_final, f, indent=4, ensure_ascii=False)
    console.print(
        f"\n[bold green]✓ CONCLUÍDO[/] — {len(dataset_final)} ação(ões) "
        f"salvas em {CSV_OUT.name} e {JSON_OUT.name}"
    )
else:
    console.print(
        "[bold red]✗ Nenhuma ação gerada.[/] "
        "Verifique os arquivos e a conexão com o Ollama."
    )
