"""
HTML Report Generator for DRL-MOBTEST multi-phase training pipeline.
Generates a single-file HTML report with:
  - Phase execution summary table
  - 4 coverage metric SVG gauges
  - Inline base64-encoded plots
  - Training summary cards
Uses only Python stdlib (string.Template, base64, pathlib).
No external CSS/JS dependencies - fully self-contained HTML.
"""

import base64
import logging
from datetime import datetime
from pathlib import Path
from string import Template
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from rlmobtest.metrics.coverage_tracker import CoverageTracker
    from rlmobtest.metrics.phase_observer import PhaseObserver
    from rlmobtest.training.metrics import TrainingMetrics

logger = logging.getLogger(__name__)

# ─────────────────────────────────────────────────────────────────────────────
# HTML TEMPLATE
# ─────────────────────────────────────────────────────────────────────────────

_REPORT_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>DRL-MOBTEST Report — $run_id</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
         background: #f0f2f5; color: #1a1a2e; line-height: 1.6; }
  .container { max-width: 1200px; margin: 0 auto; padding: 24px; }
  h1 { font-size: 28px; font-weight: 700; margin-bottom: 4px; }
  h2 { font-size: 18px; font-weight: 600; margin: 24px 0 12px; color: #333; }
  .meta { color: #666; font-size: 14px; margin-bottom: 24px; }
  .cards { display: flex; flex-wrap: wrap; gap: 12px; margin-bottom: 24px; }
  .card { background: #fff; border-radius: 10px; padding: 16px 20px;
          box-shadow: 0 1px 4px rgba(0,0,0,.08); flex: 1; min-width: 160px; }
  .card .label { font-size: 12px; color: #888; text-transform: uppercase;
                 letter-spacing: 0.5px; }
  .card .value { font-size: 26px; font-weight: 700; color: #1a1a2e; }
  .card .unit  { font-size: 13px; color: #888; }
  table { width: 100%; border-collapse: collapse; background: #fff;
          border-radius: 10px; overflow: hidden;
          box-shadow: 0 1px 4px rgba(0,0,0,.08); }
  th { background: #f7f8fa; font-size: 12px; text-transform: uppercase;
       letter-spacing: 0.5px; padding: 10px 14px; text-align: left; color: #555; }
  td { padding: 10px 14px; border-top: 1px solid #f0f0f0; font-size: 14px; }
  .badge { display: inline-block; padding: 2px 8px; border-radius: 12px;
           font-size: 12px; font-weight: 600; }
  .badge-ok   { background: #e6f9f0; color: #00875a; }
  .badge-fail { background: #fff0f0; color: #de350b; }
  .badge-skip { background: #f4f4f4; color: #888; }
  .badge-run  { background: #e8f0fe; color: #1a73e8; }
  .gauges { display: flex; flex-wrap: wrap; gap: 16px; margin-bottom: 24px; }
  .gauge-card { background: #fff; border-radius: 10px; padding: 16px;
                box-shadow: 0 1px 4px rgba(0,0,0,.08);
                text-align: center; flex: 1; min-width: 200px; }
  .gauge-card .gauge-label { font-size: 13px; color: #555; margin-top: 8px; }
  .gauge-card .gauge-value { font-size: 22px; font-weight: 700; }
  .plots { display: flex; flex-wrap: wrap; gap: 16px; }
  .plot-card { background: #fff; border-radius: 10px; padding: 16px;
               box-shadow: 0 1px 4px rgba(0,0,0,.08); flex: 1; min-width: 300px; }
  .plot-card img { width: 100%; border-radius: 6px; }
  .plot-card h3 { font-size: 14px; font-weight: 600; margin-bottom: 10px; color: #333; }
  .ep-table { width: 100%; border-collapse: collapse; background: #fff;
              border-radius: 10px; overflow: hidden;
              box-shadow: 0 1px 4px rgba(0,0,0,.08); margin-bottom: 24px; }
  .ep-table th { background: #f7f8fa; font-size: 12px; text-transform: uppercase;
                 letter-spacing: 0.5px; padding: 8px 12px; text-align: center; color: #555; }
  .ep-table td { padding: 7px 12px; border-top: 1px solid #f0f0f0; font-size: 13px;
                 text-align: center; }
  footer { text-align: center; color: #aaa; font-size: 12px; margin-top: 40px; padding: 16px; }
</style>
</head>
<body>
<div class="container">
  <h1>DRL-MOBTEST Training Report</h1>
  <p class="meta">Run ID: <strong>$run_id</strong> &nbsp;|&nbsp; Generated: $generated_at</p>

  <h2>Summary</h2>
  <div class="cards">$summary_cards</div>

  <h2>Episodes</h2>
  $episodes_table

  <h2>Phase Execution</h2>
  <table>
    <thead><tr>
      <th>Phase</th><th>Name</th><th>Status</th>
      <th>Duration</th><th>Key Output</th>
    </tr></thead>
    <tbody>$phase_rows</tbody>
  </table>

  <h2>Coverage Metrics</h2>
  <div class="gauges">$coverage_gauges</div>

  <h2>Training Plots</h2>
  <div class="plots">$plots_section</div>
</div>
<footer>Generated by DRL-MOBTEST &mdash; $generated_at</footer>
</body>
</html>
"""


def _svg_gauge(ratio: float, label: str, color: str) -> str:
    """Generate an SVG semi-circular gauge for a coverage ratio."""
    pct = min(max(ratio, 0.0), 1.0)
    # Arc parameters: semi-circle from 180° to 0°
    r = 60
    cx, cy = 80, 80
    # Start at left (180°), end at right (0°) going clockwise
    start_x, start_y = cx - r, cy
    # End point on arc at pct*180° from start
    import math

    angle = math.pi - pct * math.pi  # radians from left to right
    end_x = cx + r * math.cos(angle)
    end_y = cy - r * math.sin(angle)  # SVG y-axis inverted
    large_arc = 0  # gauge arc never exceeds 180°, so large-arc flag is always 0

    bg_path = f"M {cx - r},{cy} A {r},{r} 0 1,1 {cx + r},{cy}"
    fg_path = f"M {cx - r},{cy} A {r},{r} 0 {large_arc},1 {end_x:.1f},{end_y:.1f}"

    pct_text = f"{pct:.0%}"
    return f"""
<div class="gauge-card">
  <svg viewBox="0 0 160 100" width="160" height="100">
    <path d="{bg_path}" fill="none" stroke="#eee" stroke-width="14" stroke-linecap="round"/>
    <path d="{fg_path}" fill="none" stroke="{color}" stroke-width="14" stroke-linecap="round"/>
    <text x="{cx}" y="{cy + 10}" text-anchor="middle" font-size="18" font-weight="bold" fill="{color}">{pct_text}</text>
  </svg>
  <div class="gauge-label">{label}</div>
</div>"""


class HTMLReporter:
    """
    Generates a single-file HTML report for the DRL-MOBTEST run.
    All plots embedded as base64 PNG data URIs.
    """

    def __init__(
        self,
        observer: "PhaseObserver",
        coverage_tracker: "CoverageTracker",
        training_metrics: "TrainingMetrics | None",
        paths,
        run_id: str,
        manifest=None,
    ):
        self.observer = observer
        self.coverage = coverage_tracker
        self.metrics = training_metrics
        self.paths = paths
        self.run_id = run_id
        self.manifest = manifest

    def generate(self, output_path: Path | None = None) -> Path:
        """Build the HTML string and write to output_path."""
        if output_path is None:
            output_path = self.paths.run_path / f"report_{self.run_id}.html"

        html = Template(_REPORT_TEMPLATE).substitute(
            run_id=self.run_id,
            generated_at=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            summary_cards=self._build_summary_cards(),
            episodes_table=self._build_episodes_table(),
            phase_rows=self._build_phase_rows(),
            coverage_gauges=self._build_coverage_gauges(),
            plots_section=self._build_plots_section(),
        )

        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(html, encoding="utf-8")
        logger.info("HTML report saved: %s", output_path)
        return output_path

    def _encode_plot(self, plot_path: Path) -> str:
        """Read PNG file and return base64 data URI."""
        try:
            with open(plot_path, "rb") as f:
                b64 = base64.b64encode(f.read()).decode("ascii")
            return f"data:image/png;base64,{b64}"
        except Exception as e:
            logger.warning("Could not encode plot %s: %s", plot_path, e)
            return ""

    def _build_summary_cards(self) -> str:
        m = self.metrics
        cards = []

        def card(label, value, unit=""):
            return (
                f'<div class="card">'
                f'<div class="label">{label}</div>'
                f'<div class="value">{value}</div>'
                f'<div class="unit">{unit}</div>'
                f"</div>"
            )

        if m:
            # Truncate timedelta microseconds: "0:11:46.024731" → "0:11:46"
            dur_raw = m.get_summary().get("training_time", "")
            dur = dur_raw.split(".")[0] if "." in dur_raw else dur_raw or "N/A"
            cards.append(card("Training Time", dur))
            if m.episode_rewards:
                avg = sum(m.episode_rewards[-10:]) / min(10, len(m.episode_rewards))
                cards.append(card("Avg Reward (last 10)", f"{avg:.1f}"))

        cov = self.coverage.get_current_coverage() if self.coverage else {}
        cards.append(card("Activity Coverage", f"{cov.get('activity_coverage', 0):.0%}"))
        cards.append(card("Element Coverage", f"{cov.get('element_coverage', 0):.0%}"))

        if self.manifest:
            cards.append(card("Activities Found", len(self.manifest.activities)))

        return "\n".join(cards)

    def _build_episodes_table(self) -> str:
        """Build a per-episode breakdown table with steps and reward columns."""
        m = self.metrics
        if not m or not m.episode_rewards:
            return '<p style="color:#888;font-size:14px;">No episode data yet.</p>'

        rewards = m.episode_rewards
        lengths = m.episode_lengths if m.episode_lengths else [None] * len(rewards)

        rows = []
        for i, (reward, steps) in enumerate(zip(rewards, lengths), start=1):
            reward_color = "#00875a" if reward > 0 else "#de350b" if reward < 0 else "#555"
            steps_str = str(steps) if steps is not None else "—"
            rows.append(
                f"<tr>"
                f"<td>{i}</td>"
                f"<td>{steps_str}</td>"
                f'<td style="color:{reward_color};font-weight:600">{reward:+.0f}</td>'
                f"</tr>"
            )

        return (
            '<table class="ep-table">'
            "<thead><tr>"
            "<th>Episode</th><th>Steps</th><th>Reward</th>"
            "</tr></thead>"
            f"<tbody>{''.join(rows)}</tbody>"
            "</table>"
        )

    def _build_phase_rows(self) -> str:
        rows = []
        phase_labels = {
            "0a": "APK Manifest Parser",
            "0b": "Semantic Crawling",
            "0c": "Replay Memory Warm-up",
            "1": "RL Training",
            "2": "Enriched Transcription",
        }
        for pid in ["0a", "0b", "0c", "1", "2"]:
            record = self.observer.records.get(pid)
            if record is None:
                badge = '<span class="badge badge-skip">skipped</span>'
                dur = "—"
                output = "—"
            elif record.status == "completed":
                badge = '<span class="badge badge-ok">completed</span>'
                dur = f"{record.duration:.1f}s" if record.duration else "—"
                # Pick most informative output field
                out_items = [f"{k}: {v}" for k, v in list(record.outputs.items())[:2]]
                output = "; ".join(out_items) if out_items else "—"
            elif record.status == "failed":
                badge = '<span class="badge badge-fail">failed</span>'
                dur = f"{record.duration:.1f}s" if record.duration else "—"
                output = record.error or "—"
            else:
                badge = '<span class="badge badge-run">running</span>'
                dur = "—"
                output = "—"

            name = phase_labels.get(pid, pid)
            rows.append(
                f"<tr><td><strong>{pid}</strong></td><td>{name}</td>"
                f"<td>{badge}</td><td>{dur}</td><td>{output}</td></tr>"
            )
        return "\n".join(rows)

    def _build_coverage_gauges(self) -> str:
        cov = self.coverage.get_current_coverage() if self.coverage else {}
        gauges = [
            _svg_gauge(cov.get("activity_coverage", 0), "Activity Coverage", "#4285f4"),
            _svg_gauge(cov.get("element_coverage", 0), "Element Coverage", "#ea4335"),
            _svg_gauge(cov.get("requirement_coverage", 0), "Requirement Coverage", "#34a853"),
            _svg_gauge(cov.get("jacoco_coverage", 0), "JaCoCo Coverage", "#fbbc04"),
        ]
        return "\n".join(gauges)

    def _build_plots_section(self) -> str:
        sections = []

        # Training metrics plot
        plots_dir = self.paths.plots
        if plots_dir.exists():
            for png in sorted(plots_dir.glob(f"metrics_{self.run_id}*.png")):
                uri = self._encode_plot(png)
                if uri:
                    sections.append(
                        f'<div class="plot-card"><h3>Training Metrics</h3>'
                        f'<img src="{uri}" alt="Training Metrics"></div>'
                    )
                break

            # Coverage plot
            for png in sorted(plots_dir.glob(f"coverage_{self.run_id}*.png")):
                uri = self._encode_plot(png)
                if uri:
                    sections.append(
                        f'<div class="plot-card"><h3>Coverage Over Time</h3>'
                        f'<img src="{uri}" alt="Coverage Metrics"></div>'
                    )
                break

        if not sections:
            sections.append(
                '<div class="plot-card"><p style="color:#888;padding:40px;text-align:center">'
                "No plots available yet.</p></div>"
            )

        return "\n".join(sections)


def generate_report(
    observer: "PhaseObserver",
    coverage_tracker: "CoverageTracker",
    training_metrics: "TrainingMetrics | None",
    paths,
    run_id: str,
    manifest=None,
) -> Path:
    """Convenience function to generate and save the HTML report."""
    reporter = HTMLReporter(
        observer=observer,
        coverage_tracker=coverage_tracker,
        training_metrics=training_metrics,
        paths=paths,
        run_id=run_id,
        manifest=manifest,
    )
    return reporter.generate()
